TITLE:
sync_tensorboard: Import warnings from `pkg_resources` under given environment?

LABEL:
feature_request,c:tensorboard,stale

STATE:
closed

BODY:
* Weights and Biases version: 0.9.1
* Python version: 3.6.9
* Operating System: Linux

### Description

Putting `wandb` under a unittest in using [Bazel](https://bazel.build/).

Relates #709 - if I don't explicitly import `wandb.tensorboard` before calling `wandb.init(..., sync_tensorboard=True)`, I get a whole bunch of crufty warnings about `pkg_resources`, imports, and unclosed streams.

I can work around by importing `wandb.tensorboard`, but it would be nice to not have to copy that everywhere we use `wandb` (and hopefully we don't have to write an abstraction / wrapper on top of it...)

### What I Did

Basically, the bazel test looks something like this:
https://gist.github.com/EricCousineau-TRI/a7a2727e78fb58bab903831982596071

And I get an error like this:
```sh
$ bazel run :wandb_stub_test
...
Traceback (most recent call last):                                                                                                                                                                                 
  File "{runfiles}/{relpath}/wandb_stub_test.py", line 10
, in <module>                                                                                                                                                                                                      
    import wandb                                                                                                                                                                                                   
  File "{runfiles}/{pip_deps}/lib/python3.6/site-packages/wandb/_
_init__.py", line 53, in <module>
    from wandb.run_manager import LaunchError, Process
  File "{runfiles}/{pip_deps}/lib/python3.6/site-packages/wandb/r
un_manager.py", line 24, in <module>
    from pkg_resources import parse_version
...
  File "<frozen importlib._bootstrap_external>", line 426, in _find_module_shim
ImportWarning: Not importing directory /usr/lib/python3/dist-packages/ruamel: missing __init__
```

I can't make a min-repro on this error, and am tentative to publish too many details just yet.
Here's my attempt:

```
(
set -eux
cd $(mktemp -d)
python3 -m virtualenv -p python3 .
source bin/activate

cat > ./requirements.txt <<EOF
ruamel.yaml == 0.15.34
tensorboardX==2.0
wandb==0.9.1
EOF

pip install -r ./requirements.txt

cat > ./test.py <<EOF
import warnings

import wandb

warnings.simplefilter("error", Warning)
wandb.init(project="test", sync_tensorboard=True)
EOF

export WANDB_MODE=dryrun
python ./test.py
)
```

It doesn't reproduce the error I mention, but it does at least show some unclosed resource warnings.

In the end, this may (or most likely is) a package management issue on my side.

