TITLE:
[App] Bug: scalar chart not finding logged values

LABEL:
stale,app

STATE:
open

BODY:
**Describe the bug**
I'm trying to create a scalar chart from a logged value.

![CleanShot 2021-12-21 at 20 27 07](https://user-images.githubusercontent.com/18227298/146980253-d0b7bbbb-a0fe-4a5a-9433-adaada1f7fc1.png)

However, some scalar charts (e.g., the middle one from the top) seem not to find the corresponding values. 

![CleanShot 2021-12-21 at 20 27 42](https://user-images.githubusercontent.com/18227298/146980293-ac64d797-a344-4852-ab6a-2449e32e140e.png)

But the value is clearly logged, and visible in a simple scatter plot.

![CleanShot 2021-12-21 at 20 28 09](https://user-images.githubusercontent.com/18227298/146980323-c152dc89-7cc7-4d78-a543-068b2c2d1a8e.png)

**Expected behavior**
I would expect to see the value of the logged value, not an error.


**Operating System**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22]
     - wandb 0.12.9 
     - logs created from the wandb integration with pytorch-lightening 1.5.5
     - python 3.7.9

