TITLE:
[CLI] Error: api_key not configured (no-tty) - wandb login not working on AWS

LABEL:
cli

STATE:
closed

BODY:
I can run `wandb login` without any issues when I manually start an EC2 instance in the AWS console and execute this command.
However, when I want to execute it automatically at launch, it does not work.

```bash
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

❯ python --version
Python 3.6.11

```
Here is the beginning of my `user-data` that gets executed whenever I launch an instance via the `aws` CLI:

```bash
Content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0

--//
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config.txt"

#cloud-config
cloud_final_modules:
- [scripts-user, always]

--//
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="userdata.txt"

#!/bin/bash

output_dir=$1
log_level=$2
non_root=$3
hash=$4
config_path=$5
timestamp=$6
n_tasks=$7
batch_size=$8
workers=$9
checkpoint=placeholder

set -x  # log to /var/log/cloud-init-output.log

# needed for distributed training
export NCCL_SOCKET_IFNAME=ens3

# remove potentially broken cache folder
rm -rf "/home/${non_root}/.nv"

# create temporary folder
tmp_dir="/home/${non_root}/efs/tmp_git/${timestamp}_${hash}"
mkdir -p "${tmp_dir}"

# add SSH key for git
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
eval "$(ssh-agent -s)" &>/dev/null
ssh-add "/home/${non_root}/repositories/scripts/aws/id_rsa" &>/dev/null

# pull latest code
cd "/home/${non_root}/repositories/PCDet/" || exit
git pull

# clone repository
git clone "/home/${non_root}/repositories/PCDet/" "${tmp_dir}"

# checkout corresponding code base
cd "${tmp_dir}" || exit
git init
echo ""
git checkout --quiet --no-progress "${hash}"
echo ""
git rev-parse --quiet --short HEAD
echo ""

# set correct python path and add current code directory
export PYTHONPATH="/home/${non_root}/anaconda3/envs/PCDet/bin/python:$(pwd)"

# activate conda environment
source "/home/${non_root}/anaconda3/etc/profile.d/conda.sh"
conda activate PCDet
conda info

# ensure that output_dir exists
mkdir -p "${output_dir}"

touch "${output_dir}/platform.aws"

# wandb
"/home/${non_root}/anaconda3/envs/PCDet/bin/wandb" login

...
```

This is the error message I extracted from `/var/log/cloud-init-output.log` 
when `"/home/${non_root}/anaconda3/envs/PCDet/bin/wandb" login` (last line in snipped above) gets executed:

```bash
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/wandb/cli/cli.py", line 247, in login
    wandb.login(relogin=relogin, key=key, anonymous=anon_mode, host=host, force=True)
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 44, in login
    configured = _login(**kwargs)
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 205, in _login
    wlogin.prompt_api_key()
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 147, in prompt$
    raise UsageError("api_key not configured (no-tty).  Run wandb login")
wandb.errors.error.UsageError: api_key not configured (no-tty).  Run wandb login

Error: api_key not configured (no-tty).  Run wandb login
```

