TITLE:
[Q] Wandb pull files under a project

LABEL:
cli

STATE:
closed

BODY:
**Description**
I can't pull runs under a project with wandb pull.

**What I did**
`wandb pull -e username -p project_name`

Received the error
`Traceback (most recent call last):
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1042, in download_urls
    files = self._flatten_edges(query_result["model"]["bucket"]["files"])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\cli\cli.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\cli\cli.py", line 1346, in pull
    urls = api.download_urls(project, run=run, entity=entity)
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\apis\internal.py", line 88, in download_urls
    return self.api.download_urls(*args, **kwargs)
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\apis\normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "e:\cache\anaconda\envs\py37_base\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1042, in download_urls
    files = self._flatten_edges(query_result["model"]["bucket"]["files"])
wandb.errors.CommError: 'NoneType' object is not subscriptable

Error: 'NoneType' object is not subscriptable
`

**Environment**
` wandb --version && python --version && uname`
wandb, version 0.10.33
Python 3.7.6
MSYS_NT-10.0-19042


